######################################################################
# Automatically generated by qmake (2.01a) Wed May 15 10:42:41 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Chat.hpp
FORMS += login.ui main_view.ui
SOURCES += Chat.cpp main.cpp
